[general]
	neurons = 3
	input_neurons = 2
	output_neurons = 1
	synapsis = 5
	input_synapsis = 2
	output_synapsis = 1

[neurons]
	behaviour = 1
	behaviour_list = [1, 1, 1]
	v_thres = 150
	v_thres_list = [150, 150, 150]
	t_refract = 2
	t_refract_list = [2, 2, 2]
	input_synapsis = [2, 1, 1]
	output_synapsis = [1, 1, 1]

[synapsis]
	latency = 1
	latency_list = [1, 1, 1, 1, 1]
	weights = [0, 2, 4, 1, 3]
	training_zones = 0
	training_zones_list = [0, 0, 0, 0, 0]
	connections = [[2, 1, 1, 2, 1], [1, -1, 1], [1, 0, 1], [1, 0, 1]]
