[general]
	neurons = 3
	input_neurons = 2
	output_neurons = 2
	synapsis = 8
	input_synapsis = 2
	output_sinapsis = 2

[neurons]
	behaviour = 1
	behaviour_list = [1, 1, 1]
	v_thres = 150
	v_thres_list = [150, 150, 150]
	t_refract = 2
	t_refract_list = [2, 2, 2]
	input_synapsis = [3, 1, 2]
	output_synapsis = [1, 3, 2]

[synapsis]
	latency = 1
	latency_list = [1, 1, 1, 1]
	weights = [0, 0, 0, 0]
	training_zones = 0
	training_zones_list = [0, 0, 0, 0]
	connections = [[2, 0, 1, 1, 1], [1, 2, 1], [3, 0, 1, 2, 1, -1, 1], [2, 0, 1, -1, 1]]
