[general]
	neurons = 7
	input_neurons = 3
	output_neurons = 0
	synapsis = 13
	input_synapsis = 3
	output_synapsis = 0

[neurons]
	behaviour = 1
	behaviour_list = [1, 1, 1, 1, 1, 1, 1]
	v_thres = -1
	v_thres_list = [150, 100, 200, 150, 170, 120, 140]
	t_refract = -1
	t_refract_list = [2, 3, 1, 4, 1, 2, 3]
	input_synapsis = [1, 2, 2, 2, 2, 2, 2]
	output_synapsis = [2, 1, 2, 2, 2, 2, 1]

[synapsis]
	latency = 1
	latency_list = [1, 2, 3, 2, 1, 3, 1, 2, 5, 1, 4, 1, 1]
	weights = [1000, 50, 75, 80, 40, 90, 20, 70, 80, 40, 40, 100, 60]
	training_zones = 0
	training_zones_list = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	connections = [[1, 0, 1], [2, 1, 1, 4, 1], [1, 6, 1], [2, 4, 1, 6, 1], [2, 1, 1, 2, 1], [2, 3, 1, 5, 1], [2, 2, 1, 3, 1], [1, 5, 1]]
